// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewUserServiceInterfaceTTTT is an autogenerated mock type for the NewNewNewNewUserServiceInterfaceTTTT type
type NewNewNewNewUserServiceInterfaceTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewUserServiceInterfaceTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewUserServiceInterfaceTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewUserServiceInterfaceTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewUserServiceInterfaceTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewUserServiceInterfaceTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewUserServiceInterfaceTTTT creates a new instance of NewNewNewNewUserServiceInterfaceTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewUserServiceInterfaceTTTT(t NewNewNewNewNewUserServiceInterfaceTTTTT) *NewNewNewNewUserServiceInterfaceTTTT {
	mock := &NewNewNewNewUserServiceInterfaceTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
