// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewCityHandlerTT is an autogenerated mock type for the NewNewCityHandlerTT type
type NewNewCityHandlerTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewCityHandlerTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewCityHandlerTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewCityHandlerTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewCityHandlerTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewCityHandlerTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewCityHandlerTT creates a new instance of NewNewCityHandlerTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewCityHandlerTT(t NewNewNewCityHandlerTTT) *NewNewCityHandlerTT {
	mock := &NewNewCityHandlerTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
