// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewIDistrictHandlerT is an autogenerated mock type for the NewIDistrictHandlerT type
type NewIDistrictHandlerT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewIDistrictHandlerT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewIDistrictHandlerT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewIDistrictHandlerT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewIDistrictHandlerT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewIDistrictHandlerTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewIDistrictHandlerT creates a new instance of NewIDistrictHandlerT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewIDistrictHandlerT(t NewNewIDistrictHandlerTT) *NewIDistrictHandlerT {
	mock := &NewIDistrictHandlerT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
