// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewTransactionModelTTTT is an autogenerated mock type for the NewNewNewNewTransactionModelTTTT type
type NewNewNewNewTransactionModelTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewTransactionModelTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewTransactionModelTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewTransactionModelTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewTransactionModelTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewTransactionModelTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewTransactionModelTTTT creates a new instance of NewNewNewNewTransactionModelTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewTransactionModelTTTT(t NewNewNewNewNewTransactionModelTTTTT) *NewNewNewNewTransactionModelTTTT {
	mock := &NewNewNewNewTransactionModelTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
