// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	entities "kost/entities"
<<<<<<< HEAD
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	storage "kost/services/storage"
=======

	mock "github.com/stretchr/testify/mock"
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
)

// UserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type UserServiceInterface struct {
	mock.Mock
}

<<<<<<< HEAD
// CreateUser provides a mock function with given fields: internalRequest, files, storageProvider
func (_m *UserServiceInterface) CreateUser(internalRequest entities.CreateUserRequest, files map[string]*multipart.FileHeader, storageProvider storage.StorageInterface) (entities.InternalAuthResponse, error) {
	ret := _m.Called(internalRequest, files, storageProvider)

	var r0 entities.InternalAuthResponse
	if rf, ok := ret.Get(0).(func(entities.CreateUserRequest, map[string]*multipart.FileHeader, storage.StorageInterface) entities.InternalAuthResponse); ok {
		r0 = rf(internalRequest, files, storageProvider)
=======
// CreateUser provides a mock function with given fields: internalRequest, url
func (_m *UserServiceInterface) CreateUser(internalRequest entities.CreateUserRequest, url string) (entities.InternalAuthResponse, error) {
	ret := _m.Called(internalRequest, url)

	var r0 entities.InternalAuthResponse
	if rf, ok := ret.Get(0).(func(entities.CreateUserRequest, string) entities.InternalAuthResponse); ok {
		r0 = rf(internalRequest, url)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r0 = ret.Get(0).(entities.InternalAuthResponse)
	}

	var r1 error
<<<<<<< HEAD
	if rf, ok := ret.Get(1).(func(entities.CreateUserRequest, map[string]*multipart.FileHeader, storage.StorageInterface) error); ok {
		r1 = rf(internalRequest, files, storageProvider)
=======
	if rf, ok := ret.Get(1).(func(entities.CreateUserRequest, string) error); ok {
		r1 = rf(internalRequest, url)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

<<<<<<< HEAD
// DeleteCustomer provides a mock function with given fields: id, _a1
func (_m *UserServiceInterface) DeleteCustomer(id int, _a1 storage.StorageInterface) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, storage.StorageInterface) error); ok {
		r0 = rf(id, _a1)
=======
// DeleteCustomer provides a mock function with given fields: id
func (_m *UserServiceInterface) DeleteCustomer(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

<<<<<<< HEAD
// DeleteInternal provides a mock function with given fields: id, _a1
func (_m *UserServiceInterface) DeleteInternal(id int, _a1 storage.StorageInterface) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, storage.StorageInterface) error); ok {
		r0 = rf(id, _a1)
=======
// DeleteInternal provides a mock function with given fields: id
func (_m *UserServiceInterface) DeleteInternal(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

<<<<<<< HEAD
// GetCustomer provides a mock function with given fields: id
func (_m *UserServiceInterface) GetCustomer(id int) (entities.CustomerResponse, error) {
	ret := _m.Called(id)

	var r0 entities.CustomerResponse
	if rf, ok := ret.Get(0).(func(int) entities.CustomerResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.CustomerResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
=======
// GetAllMember provides a mock function with given fields:
func (_m *UserServiceInterface) GetAllMember() ([]entities.GetAll, error) {
	ret := _m.Called()

	var r0 []entities.GetAll
	if rf, ok := ret.Get(0).(func() []entities.GetAll); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GetAll)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

<<<<<<< HEAD
// GetInternal provides a mock function with given fields: id
func (_m *UserServiceInterface) GetInternal(id int) (entities.InternalResponse, error) {
	ret := _m.Called(id)

	var r0 entities.InternalResponse
	if rf, ok := ret.Get(0).(func(int) entities.InternalResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.InternalResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
=======
// GetbyID provides a mock function with given fields: id
func (_m *UserServiceInterface) GetbyID(id uint) (entities.CustomerResponse, error) {
	ret := _m.Called(id)

	var r0 entities.CustomerResponse
	if rf, ok := ret.Get(0).(func(uint) entities.CustomerResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.CustomerResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

<<<<<<< HEAD
// UpdateCustomer provides a mock function with given fields: customerRequest, id, files, _a3
func (_m *UserServiceInterface) UpdateCustomer(customerRequest entities.UpdateCustomerRequest, id int, files map[string]*multipart.FileHeader, _a3 storage.StorageInterface) (entities.CustomerResponse, error) {
	ret := _m.Called(customerRequest, id, files, _a3)

	var r0 entities.CustomerResponse
	if rf, ok := ret.Get(0).(func(entities.UpdateCustomerRequest, int, map[string]*multipart.FileHeader, storage.StorageInterface) entities.CustomerResponse); ok {
		r0 = rf(customerRequest, id, files, _a3)
=======
// UpdateCustomer provides a mock function with given fields: customerRequest, id, url
func (_m *UserServiceInterface) UpdateCustomer(customerRequest entities.UpdateCustomerRequest, id uint, url string) (entities.CustomerResponse, error) {
	ret := _m.Called(customerRequest, id, url)

	var r0 entities.CustomerResponse
	if rf, ok := ret.Get(0).(func(entities.UpdateCustomerRequest, uint, string) entities.CustomerResponse); ok {
		r0 = rf(customerRequest, id, url)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r0 = ret.Get(0).(entities.CustomerResponse)
	}

	var r1 error
<<<<<<< HEAD
	if rf, ok := ret.Get(1).(func(entities.UpdateCustomerRequest, int, map[string]*multipart.FileHeader, storage.StorageInterface) error); ok {
		r1 = rf(customerRequest, id, files, _a3)
=======
	if rf, ok := ret.Get(1).(func(entities.UpdateCustomerRequest, uint, string) error); ok {
		r1 = rf(customerRequest, id, url)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

<<<<<<< HEAD
// UpdateInternal provides a mock function with given fields: customerRequest, id, files, storageProvider
func (_m *UserServiceInterface) UpdateInternal(customerRequest entities.UpdateInternalRequest, id int, files map[string]*multipart.FileHeader, storageProvider storage.StorageInterface) (entities.InternalResponse, error) {
	ret := _m.Called(customerRequest, id, files, storageProvider)

	var r0 entities.InternalResponse
	if rf, ok := ret.Get(0).(func(entities.UpdateInternalRequest, int, map[string]*multipart.FileHeader, storage.StorageInterface) entities.InternalResponse); ok {
		r0 = rf(customerRequest, id, files, storageProvider)
=======
// UpdateInternal provides a mock function with given fields: customerRequest, id, url
func (_m *UserServiceInterface) UpdateInternal(customerRequest entities.UpdateInternalRequest, id uint, url string) (entities.InternalResponse, error) {
	ret := _m.Called(customerRequest, id, url)

	var r0 entities.InternalResponse
	if rf, ok := ret.Get(0).(func(entities.UpdateInternalRequest, uint, string) entities.InternalResponse); ok {
		r0 = rf(customerRequest, id, url)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r0 = ret.Get(0).(entities.InternalResponse)
	}

	var r1 error
<<<<<<< HEAD
	if rf, ok := ret.Get(1).(func(entities.UpdateInternalRequest, int, map[string]*multipart.FileHeader, storage.StorageInterface) error); ok {
		r1 = rf(customerRequest, id, files, storageProvider)
=======
	if rf, ok := ret.Get(1).(func(entities.UpdateInternalRequest, uint, string) error); ok {
		r1 = rf(customerRequest, id, url)
>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewUserServiceInterfaceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserServiceInterface creates a new instance of UserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserServiceInterface(t NewUserServiceInterfaceT) *UserServiceInterface {
	mock := &UserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
