// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewIHouseHandlerTTTT is an autogenerated mock type for the NewNewNewNewIHouseHandlerTTTT type
type NewNewNewNewIHouseHandlerTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewIHouseHandlerTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewIHouseHandlerTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewIHouseHandlerTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewIHouseHandlerTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewIHouseHandlerTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewIHouseHandlerTTTT creates a new instance of NewNewNewNewIHouseHandlerTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewIHouseHandlerTTTT(t NewNewNewNewNewIHouseHandlerTTTTT) *NewNewNewNewIHouseHandlerTTTT {
	mock := &NewNewNewNewIHouseHandlerTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
