// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewDistrictControlT is an autogenerated mock type for the NewDistrictControlT type
type NewDistrictControlT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewDistrictControlT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewDistrictControlT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewDistrictControlT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewDistrictControlT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewDistrictControlTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewDistrictControlT creates a new instance of NewDistrictControlT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewDistrictControlT(t NewNewDistrictControlTT) *NewDistrictControlT {
	mock := &NewDistrictControlT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
