// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewReviewServiceT is an autogenerated mock type for the NewReviewServiceT type
type NewReviewServiceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewReviewServiceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewReviewServiceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewReviewServiceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewReviewServiceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewReviewServiceTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewReviewServiceT creates a new instance of NewReviewServiceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewReviewServiceT(t NewNewReviewServiceTT) *NewReviewServiceT {
	mock := &NewReviewServiceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
