// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewRoomRepoTTTTT is an autogenerated mock type for the NewNewNewNewNewRoomRepoTTTTT type
type NewNewNewNewNewRoomRepoTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewRoomRepoTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRoomRepoTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewRoomRepoTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRoomRepoTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewRoomRepoTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewRoomRepoTTTTT creates a new instance of NewNewNewNewNewRoomRepoTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewRoomRepoTTTTT(t NewNewNewNewNewNewRoomRepoTTTTTT) *NewNewNewNewNewRoomRepoTTTTT {
	mock := &NewNewNewNewNewRoomRepoTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
