// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewAmenitiesHandlerTTTT is an autogenerated mock type for the NewNewNewNewAmenitiesHandlerTTTT type
type NewNewNewNewAmenitiesHandlerTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewAmenitiesHandlerTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewAmenitiesHandlerTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewAmenitiesHandlerTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewAmenitiesHandlerTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewAmenitiesHandlerTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewAmenitiesHandlerTTTT creates a new instance of NewNewNewNewAmenitiesHandlerTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewAmenitiesHandlerTTTT(t NewNewNewNewNewAmenitiesHandlerTTTTT) *NewNewNewNewAmenitiesHandlerTTTT {
	mock := &NewNewNewNewAmenitiesHandlerTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
