// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewTransactionHandlerTTTTT is an autogenerated mock type for the NewNewNewNewNewTransactionHandlerTTTTT type
type NewNewNewNewNewTransactionHandlerTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewTransactionHandlerTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewTransactionHandlerTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewTransactionHandlerTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewTransactionHandlerTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewTransactionHandlerTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewTransactionHandlerTTTTT creates a new instance of NewNewNewNewNewTransactionHandlerTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewTransactionHandlerTTTTT(t NewNewNewNewNewNewTransactionHandlerTTTTTT) *NewNewNewNewNewTransactionHandlerTTTTT {
	mock := &NewNewNewNewNewTransactionHandlerTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
