// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewStorageInterfaceTTTT is an autogenerated mock type for the NewNewNewNewStorageInterfaceTTTT type
type NewNewNewNewStorageInterfaceTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewStorageInterfaceTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewStorageInterfaceTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewStorageInterfaceTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewStorageInterfaceTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewStorageInterfaceTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewStorageInterfaceTTTT creates a new instance of NewNewNewNewStorageInterfaceTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewStorageInterfaceTTTT(t NewNewNewNewNewStorageInterfaceTTTTT) *NewNewNewNewStorageInterfaceTTTT {
	mock := &NewNewNewNewStorageInterfaceTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
