// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewReviewServiceTT is an autogenerated mock type for the NewNewReviewServiceTT type
type NewNewReviewServiceTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewReviewServiceTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewReviewServiceTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewReviewServiceTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewReviewServiceTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewReviewServiceTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewReviewServiceTT creates a new instance of NewNewReviewServiceTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewReviewServiceTT(t NewNewNewReviewServiceTTT) *NewNewReviewServiceTT {
	mock := &NewNewReviewServiceTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
