// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewUserRepositoryInterfaceTTTTT is an autogenerated mock type for the NewNewNewNewNewUserRepositoryInterfaceTTTTT type
type NewNewNewNewNewUserRepositoryInterfaceTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewUserRepositoryInterfaceTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewUserRepositoryInterfaceTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewUserRepositoryInterfaceTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewUserRepositoryInterfaceTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewUserRepositoryInterfaceTTTTT creates a new instance of NewNewNewNewNewUserRepositoryInterfaceTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewUserRepositoryInterfaceTTTTT(t NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT) *NewNewNewNewNewUserRepositoryInterfaceTTTTT {
	mock := &NewNewNewNewNewUserRepositoryInterfaceTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
