// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewTransactionServiceTTTTT is an autogenerated mock type for the NewNewNewNewNewTransactionServiceTTTTT type
type NewNewNewNewNewTransactionServiceTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewTransactionServiceTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewTransactionServiceTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewTransactionServiceTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewTransactionServiceTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewTransactionServiceTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewTransactionServiceTTTTT creates a new instance of NewNewNewNewNewTransactionServiceTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewTransactionServiceTTTTT(t NewNewNewNewNewNewTransactionServiceTTTTTT) *NewNewNewNewNewTransactionServiceTTTTT {
	mock := &NewNewNewNewNewTransactionServiceTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
