// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewHandleUserTTTTT is an autogenerated mock type for the NewNewNewNewNewHandleUserTTTTT type
type NewNewNewNewNewHandleUserTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewHandleUserTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewHandleUserTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewHandleUserTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewHandleUserTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewHandleUserTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewHandleUserTTTTT creates a new instance of NewNewNewNewNewHandleUserTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewHandleUserTTTTT(t NewNewNewNewNewNewHandleUserTTTTTT) *NewNewNewNewNewHandleUserTTTTT {
	mock := &NewNewNewNewNewHandleUserTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
