// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewReviewServiceTTTTT is an autogenerated mock type for the NewNewNewNewNewReviewServiceTTTTT type
type NewNewNewNewNewReviewServiceTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewReviewServiceTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewReviewServiceTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewReviewServiceTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewReviewServiceTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewReviewServiceTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewReviewServiceTTTTT creates a new instance of NewNewNewNewNewReviewServiceTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewReviewServiceTTTTT(t NewNewNewNewNewNewReviewServiceTTTTTT) *NewNewNewNewNewReviewServiceTTTTT {
	mock := &NewNewNewNewNewReviewServiceTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
