// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewIHouseServiceT is an autogenerated mock type for the NewIHouseServiceT type
type NewIHouseServiceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewIHouseServiceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewIHouseServiceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewIHouseServiceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewIHouseServiceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewIHouseServiceTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewIHouseServiceT creates a new instance of NewIHouseServiceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewIHouseServiceT(t NewNewIHouseServiceTT) *NewIHouseServiceT {
	mock := &NewIHouseServiceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
