// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewStorageInterfaceTTT is an autogenerated mock type for the NewNewNewStorageInterfaceTTT type
type NewNewNewStorageInterfaceTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewStorageInterfaceTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewStorageInterfaceTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewStorageInterfaceTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewStorageInterfaceTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewStorageInterfaceTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewStorageInterfaceTTT creates a new instance of NewNewNewStorageInterfaceTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewStorageInterfaceTTT(t NewNewNewNewStorageInterfaceTTTT) *NewNewNewStorageInterfaceTTT {
	mock := &NewNewNewStorageInterfaceTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
