// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewAmenitiesHandlerTTT is an autogenerated mock type for the NewNewNewAmenitiesHandlerTTT type
type NewNewNewAmenitiesHandlerTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewAmenitiesHandlerTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewAmenitiesHandlerTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewAmenitiesHandlerTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewAmenitiesHandlerTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewAmenitiesHandlerTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewAmenitiesHandlerTTT creates a new instance of NewNewNewAmenitiesHandlerTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewAmenitiesHandlerTTT(t NewNewNewNewAmenitiesHandlerTTTT) *NewNewNewAmenitiesHandlerTTT {
	mock := &NewNewNewAmenitiesHandlerTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
