// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewStorageInterfaceTTTTT is an autogenerated mock type for the NewNewNewNewNewStorageInterfaceTTTTT type
type NewNewNewNewNewStorageInterfaceTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewStorageInterfaceTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewStorageInterfaceTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewStorageInterfaceTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewStorageInterfaceTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewStorageInterfaceTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewStorageInterfaceTTTTT creates a new instance of NewNewNewNewNewStorageInterfaceTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewStorageInterfaceTTTTT(t NewNewNewNewNewNewStorageInterfaceTTTTTT) *NewNewNewNewNewStorageInterfaceTTTTT {
	mock := &NewNewNewNewNewStorageInterfaceTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
