// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewAmenitiesControlT is an autogenerated mock type for the NewAmenitiesControlT type
type NewAmenitiesControlT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewAmenitiesControlT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewAmenitiesControlT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewAmenitiesControlT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewAmenitiesControlT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewAmenitiesControlTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewAmenitiesControlT creates a new instance of NewAmenitiesControlT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewAmenitiesControlT(t NewNewAmenitiesControlTT) *NewAmenitiesControlT {
	mock := &NewAmenitiesControlT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
