// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewNewCityRepoTTTTTT is an autogenerated mock type for the NewNewNewNewNewNewCityRepoTTTTTT type
type NewNewNewNewNewNewCityRepoTTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewNewCityRepoTTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewCityRepoTTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewNewCityRepoTTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewCityRepoTTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewNewCityRepoTTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewNewCityRepoTTTTTT creates a new instance of NewNewNewNewNewNewCityRepoTTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewNewCityRepoTTTTTT(t NewNewNewNewNewNewNewCityRepoTTTTTTT) *NewNewNewNewNewNewCityRepoTTTTTT {
	mock := &NewNewNewNewNewNewCityRepoTTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
