// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewAmenitiesHandlerT is an autogenerated mock type for the NewAmenitiesHandlerT type
type NewAmenitiesHandlerT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewAmenitiesHandlerT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewAmenitiesHandlerT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewAmenitiesHandlerT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewAmenitiesHandlerT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewAmenitiesHandlerTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewAmenitiesHandlerT creates a new instance of NewAmenitiesHandlerT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewAmenitiesHandlerT(t NewNewAmenitiesHandlerTT) *NewAmenitiesHandlerT {
	mock := &NewAmenitiesHandlerT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
