// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewAmenitiesControlTT is an autogenerated mock type for the NewNewAmenitiesControlTT type
type NewNewAmenitiesControlTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewAmenitiesControlTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewAmenitiesControlTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewAmenitiesControlTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewAmenitiesControlTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewAmenitiesControlTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewAmenitiesControlTT creates a new instance of NewNewAmenitiesControlTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewAmenitiesControlTT(t NewNewNewAmenitiesControlTTT) *NewNewAmenitiesControlTT {
	mock := &NewNewAmenitiesControlTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
