// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewUserServiceInterfaceTTT is an autogenerated mock type for the NewNewNewUserServiceInterfaceTTT type
type NewNewNewUserServiceInterfaceTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewUserServiceInterfaceTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewUserServiceInterfaceTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewUserServiceInterfaceTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewUserServiceInterfaceTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewUserServiceInterfaceTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewUserServiceInterfaceTTT creates a new instance of NewNewNewUserServiceInterfaceTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewUserServiceInterfaceTTT(t NewNewNewNewUserServiceInterfaceTTTT) *NewNewNewUserServiceInterfaceTTT {
	mock := &NewNewNewUserServiceInterfaceTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
