// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	calendar "google.golang.org/api/calendar/v3"
)

// ReminderService is an autogenerated mock type for the ReminderService type
type ReminderService struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: code, BookingID
func (_m *ReminderService) CreateEvent(code string, BookingID string) (calendar.Event, error) {
	ret := _m.Called(code, BookingID)

	var r0 calendar.Event
	if rf, ok := ret.Get(0).(func(string, string) calendar.Event); ok {
		r0 = rf(code, BookingID)
	} else {
		r0 = ret.Get(0).(calendar.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(code, BookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoginUrl provides a mock function with given fields: state
func (_m *ReminderService) GetLoginUrl(state string) string {
	ret := _m.Called(state)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type NewReminderServiceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewReminderService creates a new instance of ReminderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReminderService(t NewReminderServiceT) *ReminderService {
	mock := &ReminderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
