// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewIRepoHouseTTTT is an autogenerated mock type for the NewNewNewNewIRepoHouseTTTT type
type NewNewNewNewIRepoHouseTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewIRepoHouseTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewIRepoHouseTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewIRepoHouseTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewIRepoHouseTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewIRepoHouseTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewIRepoHouseTTTT creates a new instance of NewNewNewNewIRepoHouseTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewIRepoHouseTTTT(t NewNewNewNewNewIRepoHouseTTTTT) *NewNewNewNewIRepoHouseTTTT {
	mock := &NewNewNewNewIRepoHouseTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
