// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewUserRepositoryInterfaceTT is an autogenerated mock type for the NewNewUserRepositoryInterfaceTT type
type NewNewUserRepositoryInterfaceTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewUserRepositoryInterfaceTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewUserRepositoryInterfaceTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewUserRepositoryInterfaceTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewUserRepositoryInterfaceTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewUserRepositoryInterfaceTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewUserRepositoryInterfaceTT creates a new instance of NewNewUserRepositoryInterfaceTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewUserRepositoryInterfaceTT(t NewNewNewUserRepositoryInterfaceTTT) *NewNewUserRepositoryInterfaceTT {
	mock := &NewNewUserRepositoryInterfaceTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
