// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewCityRepoTT is an autogenerated mock type for the NewNewCityRepoTT type
type NewNewCityRepoTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewCityRepoTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewCityRepoTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewCityRepoTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewCityRepoTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewCityRepoTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewCityRepoTT creates a new instance of NewNewCityRepoTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewCityRepoTT(t NewNewNewCityRepoTTT) *NewNewCityRepoTT {
	mock := &NewNewCityRepoTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
