// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewIRepoHouseTT is an autogenerated mock type for the NewNewIRepoHouseTT type
type NewNewIRepoHouseTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewIRepoHouseTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewIRepoHouseTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewIRepoHouseTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewIRepoHouseTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewIRepoHouseTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewIRepoHouseTT creates a new instance of NewNewIRepoHouseTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewIRepoHouseTT(t NewNewNewIRepoHouseTTT) *NewNewIRepoHouseTT {
	mock := &NewNewIRepoHouseTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
