// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewRepoDistrictTTTTT is an autogenerated mock type for the NewNewNewNewNewRepoDistrictTTTTT type
type NewNewNewNewNewRepoDistrictTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewRepoDistrictTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRepoDistrictTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewRepoDistrictTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRepoDistrictTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewRepoDistrictTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewRepoDistrictTTTTT creates a new instance of NewNewNewNewNewRepoDistrictTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewRepoDistrictTTTTT(t NewNewNewNewNewNewRepoDistrictTTTTTT) *NewNewNewNewNewRepoDistrictTTTTT {
	mock := &NewNewNewNewNewRepoDistrictTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
