// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewImageRepoT is an autogenerated mock type for the NewImageRepoT type
type NewImageRepoT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewImageRepoT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewImageRepoT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewImageRepoT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewImageRepoT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewImageRepoTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewImageRepoT creates a new instance of NewImageRepoT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewImageRepoT(t NewNewImageRepoTT) *NewImageRepoT {
	mock := &NewImageRepoT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
