// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ReminderHandler is an autogenerated mock type for the ReminderHandler type
type ReminderHandler struct {
	mock.Mock
}

// CreateReminder provides a mock function with given fields:
func (_m *ReminderHandler) CreateReminder() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// OauthCallback provides a mock function with given fields:
func (_m *ReminderHandler) OauthCallback() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// OauthLogin provides a mock function with given fields:
func (_m *ReminderHandler) OauthLogin() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type NewReminderHandlerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewReminderHandler creates a new instance of ReminderHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReminderHandler(t NewReminderHandlerT) *ReminderHandler {
	mock := &ReminderHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
