// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Validation is an autogenerated mock type for the Validation type
type Validation struct {
	mock.Mock
}

// Validation provides a mock function with given fields: request
func (_m *Validation) Validation(request interface{}) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewValidationT interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidation creates a new instance of Validation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidation(t NewValidationT) *Validation {
	mock := &Validation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
