// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewAuthServiceInterfaceT is an autogenerated mock type for the NewAuthServiceInterfaceT type
type NewAuthServiceInterfaceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewAuthServiceInterfaceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewAuthServiceInterfaceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewAuthServiceInterfaceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewAuthServiceInterfaceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewAuthServiceInterfaceTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewAuthServiceInterfaceT creates a new instance of NewAuthServiceInterfaceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewAuthServiceInterfaceT(t NewNewAuthServiceInterfaceTT) *NewAuthServiceInterfaceT {
	mock := &NewAuthServiceInterfaceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
