// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewUserServiceInterfaceT is an autogenerated mock type for the NewUserServiceInterfaceT type
type NewUserServiceInterfaceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewUserServiceInterfaceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewUserServiceInterfaceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewUserServiceInterfaceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewUserServiceInterfaceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewUserServiceInterfaceTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewUserServiceInterfaceT creates a new instance of NewUserServiceInterfaceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewUserServiceInterfaceT(t NewNewUserServiceInterfaceTT) *NewUserServiceInterfaceT {
	mock := &NewUserServiceInterfaceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
