// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewRoomServicesTTTT is an autogenerated mock type for the NewNewNewNewRoomServicesTTTT type
type NewNewNewNewRoomServicesTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewRoomServicesTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRoomServicesTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewRoomServicesTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRoomServicesTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewRoomServicesTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewRoomServicesTTTT creates a new instance of NewNewNewNewRoomServicesTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewRoomServicesTTTT(t NewNewNewNewNewRoomServicesTTTTT) *NewNewNewNewRoomServicesTTTT {
	mock := &NewNewNewNewRoomServicesTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
