// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewTransactionModelTT is an autogenerated mock type for the NewNewTransactionModelTT type
type NewNewTransactionModelTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewTransactionModelTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewTransactionModelTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewTransactionModelTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewTransactionModelTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewTransactionModelTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewTransactionModelTT creates a new instance of NewNewTransactionModelTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewTransactionModelTT(t NewNewNewTransactionModelTTT) *NewNewTransactionModelTT {
	mock := &NewNewTransactionModelTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
