// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewRepoAmenitiesTTTTT is an autogenerated mock type for the NewNewNewNewNewRepoAmenitiesTTTTT type
type NewNewNewNewNewRepoAmenitiesTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewRepoAmenitiesTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRepoAmenitiesTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewRepoAmenitiesTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRepoAmenitiesTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewRepoAmenitiesTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewRepoAmenitiesTTTTT creates a new instance of NewNewNewNewNewRepoAmenitiesTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewRepoAmenitiesTTTTT(t NewNewNewNewNewNewRepoAmenitiesTTTTTT) *NewNewNewNewNewRepoAmenitiesTTTTT {
	mock := &NewNewNewNewNewRepoAmenitiesTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
