// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewRepoAmenitiesTTT is an autogenerated mock type for the NewNewNewRepoAmenitiesTTT type
type NewNewNewRepoAmenitiesTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewRepoAmenitiesTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewRepoAmenitiesTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewRepoAmenitiesTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewRepoAmenitiesTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewRepoAmenitiesTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewRepoAmenitiesTTT creates a new instance of NewNewNewRepoAmenitiesTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewRepoAmenitiesTTT(t NewNewNewNewRepoAmenitiesTTTT) *NewNewNewRepoAmenitiesTTT {
	mock := &NewNewNewRepoAmenitiesTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
