// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewRoomServicesT is an autogenerated mock type for the NewRoomServicesT type
type NewRoomServicesT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewRoomServicesT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewRoomServicesT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewRoomServicesT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewRoomServicesT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewRoomServicesTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewRoomServicesT creates a new instance of NewRoomServicesT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewRoomServicesT(t NewNewRoomServicesTT) *NewRoomServicesT {
	mock := &NewRoomServicesT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
