// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewTransactionModelTTTTT is an autogenerated mock type for the NewNewNewNewNewTransactionModelTTTTT type
type NewNewNewNewNewTransactionModelTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewTransactionModelTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewTransactionModelTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewTransactionModelTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewTransactionModelTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewTransactionModelTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewTransactionModelTTTTT creates a new instance of NewNewNewNewNewTransactionModelTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewTransactionModelTTTTT(t NewNewNewNewNewNewTransactionModelTTTTTT) *NewNewNewNewNewTransactionModelTTTTT {
	mock := &NewNewNewNewNewTransactionModelTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
