// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewIRepoHouseTTT is an autogenerated mock type for the NewNewNewIRepoHouseTTT type
type NewNewNewIRepoHouseTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewIRepoHouseTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewIRepoHouseTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewIRepoHouseTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewIRepoHouseTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewIRepoHouseTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewIRepoHouseTTT creates a new instance of NewNewNewIRepoHouseTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewIRepoHouseTTT(t NewNewNewNewIRepoHouseTTTT) *NewNewNewIRepoHouseTTT {
	mock := &NewNewNewIRepoHouseTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
