// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewAmenitiesControlTTTTT is an autogenerated mock type for the NewNewNewNewNewAmenitiesControlTTTTT type
type NewNewNewNewNewAmenitiesControlTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewAmenitiesControlTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewAmenitiesControlTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewAmenitiesControlTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewAmenitiesControlTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewAmenitiesControlTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewAmenitiesControlTTTTT creates a new instance of NewNewNewNewNewAmenitiesControlTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewAmenitiesControlTTTTT(t NewNewNewNewNewNewAmenitiesControlTTTTTT) *NewNewNewNewNewAmenitiesControlTTTTT {
	mock := &NewNewNewNewNewAmenitiesControlTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
