// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewAuthServiceInterfaceTT is an autogenerated mock type for the NewNewAuthServiceInterfaceTT type
type NewNewAuthServiceInterfaceTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewAuthServiceInterfaceTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewAuthServiceInterfaceTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewAuthServiceInterfaceTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewAuthServiceInterfaceTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewAuthServiceInterfaceTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewAuthServiceInterfaceTT creates a new instance of NewNewAuthServiceInterfaceTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewAuthServiceInterfaceTT(t NewNewNewAuthServiceInterfaceTTT) *NewNewAuthServiceInterfaceTT {
	mock := &NewNewAuthServiceInterfaceTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
