// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	entities "kost/entities"

	mock "github.com/stretchr/testify/mock"
)

// ImageRepo is an autogenerated mock type for the ImageRepo type
type ImageRepo struct {
	mock.Mock
}

// CreateImage provides a mock function with given fields: new
func (_m *ImageRepo) CreateImage(new entities.Image) error {
	ret := _m.Called(new)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Image) error); ok {
		r0 = rf(new)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteImage provides a mock function with given fields: roomID, userID
func (_m *ImageRepo) DeleteImage(roomID uint, userID uint) error {
	ret := _m.Called(roomID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewImageRepoT interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageRepo creates a new instance of ImageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageRepo(t NewImageRepoT) *ImageRepo {
	mock := &ImageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
