// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewReviewModelTT is an autogenerated mock type for the NewNewReviewModelTT type
type NewNewReviewModelTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewReviewModelTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewReviewModelTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewReviewModelTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewReviewModelTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewReviewModelTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewReviewModelTT creates a new instance of NewNewReviewModelTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewReviewModelTT(t NewNewNewReviewModelTTT) *NewNewReviewModelTT {
	mock := &NewNewReviewModelTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
