// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewNewIHouseHandlerTTTTTT is an autogenerated mock type for the NewNewNewNewNewNewIHouseHandlerTTTTTT type
type NewNewNewNewNewNewIHouseHandlerTTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewNewIHouseHandlerTTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewIHouseHandlerTTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewNewIHouseHandlerTTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewIHouseHandlerTTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewNewIHouseHandlerTTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewNewIHouseHandlerTTTTTT creates a new instance of NewNewNewNewNewNewIHouseHandlerTTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewNewIHouseHandlerTTTTTT(t NewNewNewNewNewNewNewIHouseHandlerTTTTTTT) *NewNewNewNewNewNewIHouseHandlerTTTTTT {
	mock := &NewNewNewNewNewNewIHouseHandlerTTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
