// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewRepoFacilityTTTT is an autogenerated mock type for the NewNewNewNewRepoFacilityTTTT type
type NewNewNewNewRepoFacilityTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewRepoFacilityTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRepoFacilityTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewRepoFacilityTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRepoFacilityTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewRepoFacilityTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewRepoFacilityTTTT creates a new instance of NewNewNewNewRepoFacilityTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewRepoFacilityTTTT(t NewNewNewNewNewRepoFacilityTTTTT) *NewNewNewNewRepoFacilityTTTT {
	mock := &NewNewNewNewRepoFacilityTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
