// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewTransactionHandlerTTT is an autogenerated mock type for the NewNewNewTransactionHandlerTTT type
type NewNewNewTransactionHandlerTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewTransactionHandlerTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewTransactionHandlerTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewTransactionHandlerTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewTransactionHandlerTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewTransactionHandlerTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewTransactionHandlerTTT creates a new instance of NewNewNewTransactionHandlerTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewTransactionHandlerTTT(t NewNewNewNewTransactionHandlerTTTT) *NewNewNewTransactionHandlerTTT {
	mock := &NewNewNewTransactionHandlerTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
