// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewReviewModelT is an autogenerated mock type for the NewReviewModelT type
type NewReviewModelT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewReviewModelT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewReviewModelT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewReviewModelT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewReviewModelT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewReviewModelTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewReviewModelT creates a new instance of NewReviewModelT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewReviewModelT(t NewNewReviewModelTT) *NewReviewModelT {
	mock := &NewReviewModelT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
