// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewIDistrictHandlerTTTTT is an autogenerated mock type for the NewNewNewNewNewIDistrictHandlerTTTTT type
type NewNewNewNewNewIDistrictHandlerTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewIDistrictHandlerTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewIDistrictHandlerTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewIDistrictHandlerTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewIDistrictHandlerTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewIDistrictHandlerTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewIDistrictHandlerTTTTT creates a new instance of NewNewNewNewNewIDistrictHandlerTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewIDistrictHandlerTTTTT(t NewNewNewNewNewNewIDistrictHandlerTTTTTT) *NewNewNewNewNewIDistrictHandlerTTTTT {
	mock := &NewNewNewNewNewIDistrictHandlerTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
