// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewIDistrictHandlerTT is an autogenerated mock type for the NewNewIDistrictHandlerTT type
type NewNewIDistrictHandlerTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewIDistrictHandlerTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewIDistrictHandlerTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewIDistrictHandlerTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewIDistrictHandlerTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewIDistrictHandlerTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewIDistrictHandlerTT creates a new instance of NewNewIDistrictHandlerTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewIDistrictHandlerTT(t NewNewNewIDistrictHandlerTTT) *NewNewIDistrictHandlerTT {
	mock := &NewNewIDistrictHandlerTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
