// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewDistrictControlTTTTT is an autogenerated mock type for the NewNewNewNewNewDistrictControlTTTTT type
type NewNewNewNewNewDistrictControlTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewDistrictControlTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewDistrictControlTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewDistrictControlTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewDistrictControlTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewDistrictControlTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewDistrictControlTTTTT creates a new instance of NewNewNewNewNewDistrictControlTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewDistrictControlTTTTT(t NewNewNewNewNewNewDistrictControlTTTTTT) *NewNewNewNewNewDistrictControlTTTTT {
	mock := &NewNewNewNewNewDistrictControlTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
