// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT is an autogenerated mock type for the NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT type
type NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewNewUserRepositoryInterfaceTTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewNewUserRepositoryInterfaceTTTTTT creates a new instance of NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewNewUserRepositoryInterfaceTTTTTT(t NewNewNewNewNewNewNewUserRepositoryInterfaceTTTTTTT) *NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT {
	mock := &NewNewNewNewNewNewUserRepositoryInterfaceTTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
