// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewRoomHanlderTTT is an autogenerated mock type for the NewNewNewRoomHanlderTTT type
type NewNewNewRoomHanlderTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewRoomHanlderTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewRoomHanlderTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewRoomHanlderTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewRoomHanlderTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewRoomHanlderTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewRoomHanlderTTT creates a new instance of NewNewNewRoomHanlderTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewRoomHanlderTTT(t NewNewNewNewRoomHanlderTTTT) *NewNewNewRoomHanlderTTT {
	mock := &NewNewNewRoomHanlderTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
