// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewRepoDistrictTT is an autogenerated mock type for the NewNewRepoDistrictTT type
type NewNewRepoDistrictTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewRepoDistrictTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewRepoDistrictTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewRepoDistrictTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewRepoDistrictTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewRepoDistrictTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewRepoDistrictTT creates a new instance of NewNewRepoDistrictTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewRepoDistrictTT(t NewNewNewRepoDistrictTTT) *NewNewRepoDistrictTT {
	mock := &NewNewRepoDistrictTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
