// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewImageRepoTT is an autogenerated mock type for the NewNewImageRepoTT type
type NewNewImageRepoTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewImageRepoTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewImageRepoTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewImageRepoTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewImageRepoTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewImageRepoTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewImageRepoTT creates a new instance of NewNewImageRepoTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewImageRepoTT(t NewNewNewImageRepoTTT) *NewNewImageRepoTT {
	mock := &NewNewImageRepoTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
