// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewFacilityHandlerTTTTT is an autogenerated mock type for the NewNewNewNewNewFacilityHandlerTTTTT type
type NewNewNewNewNewFacilityHandlerTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewFacilityHandlerTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewFacilityHandlerTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewFacilityHandlerTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewFacilityHandlerTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewFacilityHandlerTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewFacilityHandlerTTTTT creates a new instance of NewNewNewNewNewFacilityHandlerTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewFacilityHandlerTTTTT(t NewNewNewNewNewNewFacilityHandlerTTTTTT) *NewNewNewNewNewFacilityHandlerTTTTT {
	mock := &NewNewNewNewNewFacilityHandlerTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
