// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewIHouseHandlerTTTTT is an autogenerated mock type for the NewNewNewNewNewIHouseHandlerTTTTT type
type NewNewNewNewNewIHouseHandlerTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewIHouseHandlerTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewIHouseHandlerTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewIHouseHandlerTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewIHouseHandlerTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewIHouseHandlerTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewIHouseHandlerTTTTT creates a new instance of NewNewNewNewNewIHouseHandlerTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewIHouseHandlerTTTTT(t NewNewNewNewNewNewIHouseHandlerTTTTTT) *NewNewNewNewNewIHouseHandlerTTTTT {
	mock := &NewNewNewNewNewIHouseHandlerTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
