// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// TransactionHandler is an autogenerated mock type for the TransactionHandler type
type TransactionHandler struct {
	mock.Mock
}

// GetAllTransactionbyConsultant provides a mock function with given fields: c
func (_m *TransactionHandler) GetAllTransactionbyConsultant(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTransactionbyCustomer provides a mock function with given fields: c
func (_m *TransactionHandler) GetAllTransactionbyCustomer(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

<<<<<<< HEAD
=======
// GetAllTransactionbyKost provides a mock function with given fields: c
func (_m *TransactionHandler) GetAllTransactionbyKost(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
// InsertTransaction provides a mock function with given fields: c
func (_m *TransactionHandler) InsertTransaction(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

<<<<<<< HEAD
=======
// UpdateStatus provides a mock function with given fields: c
func (_m *TransactionHandler) UpdateStatus(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

>>>>>>> 3d2f172cae4224571053c1b5658836fe1402c6a9
// UpdateTransaction provides a mock function with given fields: c
func (_m *TransactionHandler) UpdateTransaction(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewTransactionHandlerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionHandler creates a new instance of TransactionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionHandler(t NewTransactionHandlerT) *TransactionHandler {
	mock := &TransactionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
