// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewUserRepositoryInterfaceTTT is an autogenerated mock type for the NewNewNewUserRepositoryInterfaceTTT type
type NewNewNewUserRepositoryInterfaceTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewUserRepositoryInterfaceTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewUserRepositoryInterfaceTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewUserRepositoryInterfaceTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewUserRepositoryInterfaceTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewUserRepositoryInterfaceTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewUserRepositoryInterfaceTTT creates a new instance of NewNewNewUserRepositoryInterfaceTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewUserRepositoryInterfaceTTT(t NewNewNewNewUserRepositoryInterfaceTTTT) *NewNewNewUserRepositoryInterfaceTTT {
	mock := &NewNewNewUserRepositoryInterfaceTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
