// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewCityHandlerTTTTT is an autogenerated mock type for the NewNewNewNewNewCityHandlerTTTTT type
type NewNewNewNewNewCityHandlerTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewCityHandlerTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewCityHandlerTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewCityHandlerTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewCityHandlerTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewCityHandlerTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewCityHandlerTTTTT creates a new instance of NewNewNewNewNewCityHandlerTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewCityHandlerTTTTT(t NewNewNewNewNewNewCityHandlerTTTTTT) *NewNewNewNewNewCityHandlerTTTTT {
	mock := &NewNewNewNewNewCityHandlerTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
