// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewHandleUserTT is an autogenerated mock type for the NewNewHandleUserTT type
type NewNewHandleUserTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewHandleUserTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewHandleUserTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewHandleUserTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewHandleUserTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewHandleUserTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewHandleUserTT creates a new instance of NewNewHandleUserTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewHandleUserTT(t NewNewNewHandleUserTTT) *NewNewHandleUserTT {
	mock := &NewNewHandleUserTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
