// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewHandleUserT is an autogenerated mock type for the NewHandleUserT type
type NewHandleUserT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewHandleUserT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewHandleUserT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewHandleUserT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewHandleUserT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewHandleUserTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewHandleUserT creates a new instance of NewHandleUserT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewHandleUserT(t NewNewHandleUserTT) *NewHandleUserT {
	mock := &NewHandleUserT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
