// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewFacilityHandlerTTT is an autogenerated mock type for the NewNewNewFacilityHandlerTTT type
type NewNewNewFacilityHandlerTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewFacilityHandlerTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewFacilityHandlerTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewFacilityHandlerTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewFacilityHandlerTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewFacilityHandlerTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewFacilityHandlerTTT creates a new instance of NewNewNewFacilityHandlerTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewFacilityHandlerTTT(t NewNewNewNewFacilityHandlerTTTT) *NewNewNewFacilityHandlerTTT {
	mock := &NewNewNewFacilityHandlerTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
