// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewCityRepoT is an autogenerated mock type for the NewCityRepoT type
type NewCityRepoT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewCityRepoT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewCityRepoT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewCityRepoT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewCityRepoT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewCityRepoTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewCityRepoT creates a new instance of NewCityRepoT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewCityRepoT(t NewNewCityRepoTT) *NewCityRepoT {
	mock := &NewCityRepoT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
