// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewRepoAmenitiesTTTT is an autogenerated mock type for the NewNewNewNewRepoAmenitiesTTTT type
type NewNewNewNewRepoAmenitiesTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewRepoAmenitiesTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRepoAmenitiesTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewRepoAmenitiesTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRepoAmenitiesTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewRepoAmenitiesTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewRepoAmenitiesTTTT creates a new instance of NewNewNewNewRepoAmenitiesTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewRepoAmenitiesTTTT(t NewNewNewNewNewRepoAmenitiesTTTTT) *NewNewNewNewRepoAmenitiesTTTT {
	mock := &NewNewNewNewRepoAmenitiesTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
