// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewRepoDistrictTTTT is an autogenerated mock type for the NewNewNewNewRepoDistrictTTTT type
type NewNewNewNewRepoDistrictTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewRepoDistrictTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRepoDistrictTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewRepoDistrictTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewRepoDistrictTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewRepoDistrictTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewRepoDistrictTTTT creates a new instance of NewNewNewNewRepoDistrictTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewRepoDistrictTTTT(t NewNewNewNewNewRepoDistrictTTTTT) *NewNewNewNewRepoDistrictTTTT {
	mock := &NewNewNewNewRepoDistrictTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
