// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewRoomRepoTT is an autogenerated mock type for the NewNewRoomRepoTT type
type NewNewRoomRepoTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewRoomRepoTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewRoomRepoTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewRoomRepoTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewRoomRepoTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewRoomRepoTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewRoomRepoTT creates a new instance of NewNewRoomRepoTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewRoomRepoTT(t NewNewNewRoomRepoTTT) *NewNewRoomRepoTT {
	mock := &NewNewRoomRepoTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
