// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewTransactionHandlerTTTT is an autogenerated mock type for the NewNewNewNewTransactionHandlerTTTT type
type NewNewNewNewTransactionHandlerTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewTransactionHandlerTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewTransactionHandlerTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewTransactionHandlerTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewTransactionHandlerTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewTransactionHandlerTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewTransactionHandlerTTTT creates a new instance of NewNewNewNewTransactionHandlerTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewTransactionHandlerTTTT(t NewNewNewNewNewTransactionHandlerTTTTT) *NewNewNewNewTransactionHandlerTTTT {
	mock := &NewNewNewNewTransactionHandlerTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
