// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewRepoFacilityTTTTT is an autogenerated mock type for the NewNewNewNewNewRepoFacilityTTTTT type
type NewNewNewNewNewRepoFacilityTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewRepoFacilityTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRepoFacilityTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewRepoFacilityTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRepoFacilityTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewRepoFacilityTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewRepoFacilityTTTTT creates a new instance of NewNewNewNewNewRepoFacilityTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewRepoFacilityTTTTT(t NewNewNewNewNewNewRepoFacilityTTTTTT) *NewNewNewNewNewRepoFacilityTTTTT {
	mock := &NewNewNewNewNewRepoFacilityTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
