// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewNewUserServiceInterfaceTTTTTT is an autogenerated mock type for the NewNewNewNewNewNewUserServiceInterfaceTTTTTT type
type NewNewNewNewNewNewUserServiceInterfaceTTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewNewUserServiceInterfaceTTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewUserServiceInterfaceTTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewNewUserServiceInterfaceTTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewUserServiceInterfaceTTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewNewUserServiceInterfaceTTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewNewUserServiceInterfaceTTTTTT creates a new instance of NewNewNewNewNewNewUserServiceInterfaceTTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewNewUserServiceInterfaceTTTTTT(t NewNewNewNewNewNewNewUserServiceInterfaceTTTTTTT) *NewNewNewNewNewNewUserServiceInterfaceTTTTTT {
	mock := &NewNewNewNewNewNewUserServiceInterfaceTTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
