// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewRepoDistrictTTT is an autogenerated mock type for the NewNewNewRepoDistrictTTT type
type NewNewNewRepoDistrictTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewRepoDistrictTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewRepoDistrictTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewRepoDistrictTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewRepoDistrictTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewRepoDistrictTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewRepoDistrictTTT creates a new instance of NewNewNewRepoDistrictTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewRepoDistrictTTT(t NewNewNewNewRepoDistrictTTTT) *NewNewNewRepoDistrictTTT {
	mock := &NewNewNewRepoDistrictTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
