// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewTransactionServiceTT is an autogenerated mock type for the NewNewTransactionServiceTT type
type NewNewTransactionServiceTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewTransactionServiceTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewTransactionServiceTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewTransactionServiceTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewTransactionServiceTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewTransactionServiceTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewTransactionServiceTT creates a new instance of NewNewTransactionServiceTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewTransactionServiceTT(t NewNewNewTransactionServiceTTT) *NewNewTransactionServiceTT {
	mock := &NewNewTransactionServiceTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
