// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewIHouseServiceTTTT is an autogenerated mock type for the NewNewNewNewIHouseServiceTTTT type
type NewNewNewNewIHouseServiceTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewIHouseServiceTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewIHouseServiceTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewIHouseServiceTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewIHouseServiceTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewIHouseServiceTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewIHouseServiceTTTT creates a new instance of NewNewNewNewIHouseServiceTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewIHouseServiceTTTT(t NewNewNewNewNewIHouseServiceTTTTT) *NewNewNewNewIHouseServiceTTTT {
	mock := &NewNewNewNewIHouseServiceTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
