// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewCityRepoTTTTT is an autogenerated mock type for the NewNewNewNewNewCityRepoTTTTT type
type NewNewNewNewNewCityRepoTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewCityRepoTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewCityRepoTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewCityRepoTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewCityRepoTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewCityRepoTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewCityRepoTTTTT creates a new instance of NewNewNewNewNewCityRepoTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewCityRepoTTTTT(t NewNewNewNewNewNewCityRepoTTTTTT) *NewNewNewNewNewCityRepoTTTTT {
	mock := &NewNewNewNewNewCityRepoTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
