// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewUserRepositoryInterfaceT is an autogenerated mock type for the NewUserRepositoryInterfaceT type
type NewUserRepositoryInterfaceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewUserRepositoryInterfaceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewUserRepositoryInterfaceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewUserRepositoryInterfaceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewUserRepositoryInterfaceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewUserRepositoryInterfaceTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewUserRepositoryInterfaceT creates a new instance of NewUserRepositoryInterfaceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewUserRepositoryInterfaceT(t NewNewUserRepositoryInterfaceTT) *NewUserRepositoryInterfaceT {
	mock := &NewUserRepositoryInterfaceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
