// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewNewAuthServiceInterfaceTTTTTT is an autogenerated mock type for the NewNewNewNewNewNewAuthServiceInterfaceTTTTTT type
type NewNewNewNewNewNewAuthServiceInterfaceTTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewNewAuthServiceInterfaceTTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewAuthServiceInterfaceTTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewNewAuthServiceInterfaceTTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewNewAuthServiceInterfaceTTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewNewAuthServiceInterfaceTTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewNewAuthServiceInterfaceTTTTTT creates a new instance of NewNewNewNewNewNewAuthServiceInterfaceTTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewNewAuthServiceInterfaceTTTTTT(t NewNewNewNewNewNewNewAuthServiceInterfaceTTTTTTT) *NewNewNewNewNewNewAuthServiceInterfaceTTTTTT {
	mock := &NewNewNewNewNewNewAuthServiceInterfaceTTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
