// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewUserRepositoryInterfaceTTTT is an autogenerated mock type for the NewNewNewNewUserRepositoryInterfaceTTTT type
type NewNewNewNewUserRepositoryInterfaceTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewUserRepositoryInterfaceTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewUserRepositoryInterfaceTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewUserRepositoryInterfaceTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewUserRepositoryInterfaceTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewUserRepositoryInterfaceTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewUserRepositoryInterfaceTTTT creates a new instance of NewNewNewNewUserRepositoryInterfaceTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewUserRepositoryInterfaceTTTT(t NewNewNewNewNewUserRepositoryInterfaceTTTTT) *NewNewNewNewUserRepositoryInterfaceTTTT {
	mock := &NewNewNewNewUserRepositoryInterfaceTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
