// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewNewRoomHanlderTTTTT is an autogenerated mock type for the NewNewNewNewNewRoomHanlderTTTTT type
type NewNewNewNewNewRoomHanlderTTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewNewRoomHanlderTTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRoomHanlderTTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewNewRoomHanlderTTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewNewRoomHanlderTTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewNewRoomHanlderTTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewNewRoomHanlderTTTTT creates a new instance of NewNewNewNewNewRoomHanlderTTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewNewRoomHanlderTTTTT(t NewNewNewNewNewNewRoomHanlderTTTTTT) *NewNewNewNewNewRoomHanlderTTTTT {
	mock := &NewNewNewNewNewRoomHanlderTTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
