// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewStorageInterfaceTT is an autogenerated mock type for the NewNewStorageInterfaceTT type
type NewNewStorageInterfaceTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewStorageInterfaceTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewStorageInterfaceTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewStorageInterfaceTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewStorageInterfaceTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewStorageInterfaceTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewStorageInterfaceTT creates a new instance of NewNewStorageInterfaceTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewStorageInterfaceTT(t NewNewNewStorageInterfaceTTT) *NewNewStorageInterfaceTT {
	mock := &NewNewStorageInterfaceTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
