// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewValidationT is an autogenerated mock type for the NewValidationT type
type NewValidationT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewValidationT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewValidationT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewValidationT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewValidationT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewValidationTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewValidationT creates a new instance of NewValidationT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewValidationT(t NewNewValidationTT) *NewValidationT {
	mock := &NewValidationT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
