// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewCityHandlerTTTT is an autogenerated mock type for the NewNewNewNewCityHandlerTTTT type
type NewNewNewNewCityHandlerTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewCityHandlerTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewCityHandlerTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewCityHandlerTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewCityHandlerTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewCityHandlerTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewCityHandlerTTTT creates a new instance of NewNewNewNewCityHandlerTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewCityHandlerTTTT(t NewNewNewNewNewCityHandlerTTTTT) *NewNewNewNewCityHandlerTTTT {
	mock := &NewNewNewNewCityHandlerTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
