// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewFacilityControlT is an autogenerated mock type for the NewFacilityControlT type
type NewFacilityControlT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewFacilityControlT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewFacilityControlT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewFacilityControlT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewFacilityControlT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewFacilityControlTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewFacilityControlT creates a new instance of NewFacilityControlT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewFacilityControlT(t NewNewFacilityControlTT) *NewFacilityControlT {
	mock := &NewFacilityControlT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
