// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewNewNewNewFacilityControlTTTT is an autogenerated mock type for the NewNewNewNewFacilityControlTTTT type
type NewNewNewNewFacilityControlTTTT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewNewNewNewFacilityControlTTTT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewNewNewNewFacilityControlTTTT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewNewNewNewFacilityControlTTTT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewNewNewNewFacilityControlTTTT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewNewNewNewFacilityControlTTTTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewNewNewNewFacilityControlTTTT creates a new instance of NewNewNewNewFacilityControlTTTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewNewNewNewFacilityControlTTTT(t NewNewNewNewNewFacilityControlTTTTT) *NewNewNewNewFacilityControlTTTT {
	mock := &NewNewNewNewFacilityControlTTTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
