// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewIHouseHandlerT is an autogenerated mock type for the NewIHouseHandlerT type
type NewIHouseHandlerT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewIHouseHandlerT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewIHouseHandlerT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewIHouseHandlerT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewIHouseHandlerT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewIHouseHandlerTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewIHouseHandlerT creates a new instance of NewIHouseHandlerT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewIHouseHandlerT(t NewNewIHouseHandlerTT) *NewIHouseHandlerT {
	mock := &NewIHouseHandlerT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
